### ISSUE TITLE
Change PPF confidence score

### ISSUE THREAD

**Issue by ChristianXEder** [v4r-tuwien/verefine_pipeline#4]
Densefusion score and PPF score are currently not comparable. PPF score is multiplied by the factor of 35 to be not discarded from the hsr-grasping node.

**Comment by hoenigpeter** [comment]
@lexihaberl status? can we close it?

**Comment by lexihaberl** [comment]
Yes, this issue is not relevant anymore since we don't use PPF and/or Verefine anymore
