### ISSUE TITLE
Update Docker Image to newer CUDA versions

### ISSUE THREAD

**Issue by lexihaberl** [v4r-tuwien/verefine_pipeline#5]
NVIDIA unfortunately removed the CUDA docker images that we currently use in the Verefine pipeline, which means that they cannot be built. If we still want to be able to use the VeRefine pipeline we will need to update our docker images. 

Just bumping the CUDA image versions is not enough: Cython breaks when doing that (reports CompileErrors). Other stuff probably also breaks.

**Comment by jibweb** [comment]
Could you specify which Dockerfile don't build anymore?

**Comment by lexihaberl** [comment]
In the Bremen branch:
- src/maskRCNN/Dockerfile
- src/PPF/Dockerfile
- src/task/Dockerfile (also fails but not because of NVIDIA stuff)

src/verefine/Dockerfile does get built but I didn't check whether it actually runs.

**Comment by lexihaberl** [comment]
Updating the Docker images has been deemed infeasible, because we still have Python 2 Code and would need to port this to Python 3. Additionally we would need to modify the code for the new CUDA and Tensorflow version. We will  use the [GDR-Net Pipeline](https://github.com/v4r-tuwien/gdrnet_pipeline/) instead.
